services:
  stack-agent:
    image: ghcr.io/rcarson/stack-agent:latest
    restart: unless-stopped
    environment:
      - STACK_AGENT_DEFAULT_TOKEN=${STACK_AGENT_DEFAULT_TOKEN}
      - STACK_AGENT_LOG_LEVEL=info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yaml:/opt/stack-agent/config.yaml:ro
      - ./data:/opt/stack-agent/data
